//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarframeWorldStateTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarframeWorldStateTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;modes&quot;: {
        ///    &quot;PVPMODE_ALL&quot;: &quot;Any Mode&quot;,
        ///    &quot;PVPMODE_DEATHMATCH&quot;: &quot;Annihilation&quot;,
        ///    &quot;PVPMODE_TEAMDEATHMATCH&quot;: &quot;Team Annihilation&quot;,
        ///    &quot;PVPMODE_NONE&quot;: &quot;None&quot;,
        ///    &quot;PVPMODE_CAPTURETHEFLAG&quot;: &quot;Capture the Cephalon&quot;,
        ///    &quot;PVPMODE_SPEEDBALL&quot;: &quot;Lunaro&quot;,
        ///  },
        ///  &quot;categories&quot;: {
        ///    &quot;PVPChallengeTypeCategory_WEEKLY&quot;: &quot;Weekly&quot;,
        ///    &quot;PVPChallengeTypeCategory_WEEKLY_ROOT&quot;: &quot;weekly_root&quot;,
        ///    &quot;PVPChallengeTypeCategory_DAILY&quot;: &quot;Daily&quot;,
        ///    &quot;PVPChallengeTypeCategory_DAILY_ROOT&quot;: &quot;daily_root&quot;,
        ///    &quot;PV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string conclaveData {
            get {
                return ResourceManager.GetString("conclaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;tags&quot;: {
        ///    &quot;KelaEvent&quot;: {
        ///      &quot;value&quot;: &quot;Operation: Rathuum&quot;
        ///    }, &quot;KelaEventB&quot; : {
        ///      &quot;value&quot;: &quot;Operation: Rathuum pt. 2&quot;
        ///    }, &quot;KelaEventBonus&quot;: {
        ///      &quot;value&quot;: &quot;Endless Rathuum&quot;
        ///    }
        ///  },
        ///  &quot;scoreVariables&quot;: {
        ///    &quot;KelaEvent&quot;: {
        ///      &quot;value&quot;: {
        ///        &quot;value&quot;: &quot;100 Judgement Points&quot;
        ///      }
        ///    }
        ///  },
        ///  &quot;scoreMaxTags&quot;: {
        ///    &quot;KelaEventMax&quot;: {
        ///      &quot;value&quot;: {
        ///        &quot;value&quot;: &quot;100 Judgement Points&quot;
        ///      }
        ///    }
        ///  }
        ///}.
        /// </summary>
        public static string eventsData {
            get {
                return ResourceManager.GetString("eventsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FC_GRINEER&quot;: {
        ///    &quot;value&quot;: &quot;Grineer&quot;
        ///  }
        ///  , &quot;FC_CORPUS&quot;: {
        ///    &quot;value&quot;: &quot;Corpus&quot;
        ///  }
        ///  , &quot;FC_INFESTATION&quot;: {
        ///    &quot;value&quot;: &quot;Infested&quot;
        ///  }
        ///  , &quot;FC_CORRUPTED&quot;: {
        ///    &quot;value&quot;: &quot;Corrupted&quot;
        ///  }
        ///  , &quot;FC_OROKIN&quot;: {
        ///    &quot;value&quot;: &quot;Orokin&quot;
        ///  }
        ///}.
        /// </summary>
        public static string factionsData {
            get {
                return ResourceManager.GetString("factionsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;VoidT1&quot; : {
        ///    &quot;value&quot; : &quot;Lith (Tier 1)&quot;,
        ///    &quot;num&quot; : 1
        ///  }
        ///  , &quot;VoidT2&quot; : {
        ///    &quot;value&quot; : &quot;Meso (Tier 2)&quot;,
        ///    &quot;num&quot; : 2
        ///  }
        ///  , &quot;VoidT3&quot; : {
        ///    &quot;value&quot; : &quot;Neo  (Tier 3)&quot;,
        ///    &quot;num&quot; : 3
        ///  }
        ///  , &quot;VoidT4&quot; : {
        ///    &quot;value&quot; : &quot;Axi  (Tier 4)&quot;,
        ///    &quot;num&quot; : 4
        ///  }
        ///}.
        /// </summary>
        public static string fissureModifiers {
            get {
                return ResourceManager.GetString("fissureModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;/lotus/characters/tenno/accessory/scarves/grnbannerscarf/grnbannerscarfitem&quot;: &quot;Vanquished Banner&quot;, 
        ///    &quot;/lotus/characters/tenno/accessory/scarves/u17intermscarf/u17intermscarfitem&quot;: &quot;Udyat Syandana&quot;, 
        ///    &quot;/lotus/language/alerts/aladcargoevent&quot;: &quot;Suspicious Shipment&quot;, 
        ///    &quot;/lotus/language/alerts/alertrewardcategoryaura&quot;: &quot;Aura&quot;, 
        ///    &quot;/lotus/language/alerts/alertrewardcategoryblueprint&quot;: &quot;Blueprint&quot;, 
        ///    &quot;/lotus/language/alerts/alertrewardcategoryitem&quot;: &quot;Item&quot;, 
        ///    &quot;/lotus/language/alerts/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;MT_EXCAVATE&quot;: {
        ///   &quot;value&quot;: &quot;Excavation&quot;
        /// },
        /// &quot;MT_SABOTAGE&quot;: {
        ///   &quot;value&quot;: &quot;Sabotage&quot;
        /// },
        /// &quot;MT_MOBILE_DEFENSE&quot;: {
        ///   &quot;value&quot;: &quot;Mobile Defense&quot;
        /// },
        /// &quot;MT_ASSASSINATION&quot;: {
        ///   &quot;value&quot;: &quot;Assassination&quot;
        /// },
        /// &quot;MT_EXTERMINATION&quot;: {
        ///   &quot;value&quot;: &quot;Extermination&quot;
        /// },
        /// &quot;MT_HIVE&quot;: {
        ///   &quot;value&quot;: &quot;Hive&quot;
        /// },
        /// &quot;MT_DEFENSE&quot;: {
        ///   &quot;value&quot;: &quot;Defense&quot;
        /// },
        /// &quot;MT_TERRITORY&quot;: {
        ///   &quot;value&quot;: &quot;Interception&quot;
        /// },
        /// &quot;MT_ARENA&quot;: {
        ///   &quot;value&quot;: &quot;Rathuum&quot;
        /// },
        /// &quot;MT_PVP&quot;: {
        ///   &quot;value&quot;: &quot;Conclave&quot;
        /// },
        /// &quot;MT_RESC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string missionTypes {
            get {
                return ResourceManager.GetString("missionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;MULTIPLY&quot; : {
        ///    &quot;value&quot; : &quot;is multiplied by&quot;
        ///  }
        ///}.
        /// </summary>
        public static string operationTypes {
            get {
                return ResourceManager.GetString("operationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;regions&quot;: [
        ///    &quot;0&quot;
        ///    , &quot;1&quot;
        ///    , &quot;2&quot;
        ///    , &quot;Mars&quot;
        ///    , &quot;Jupiter&quot;
        ///    , &quot;Saturn&quot;
        ///    , &quot;6&quot;
        ///    , &quot;7&quot;
        ///    , &quot;Pluto&quot;
        ///    , &quot;Ceres&quot;
        ///    , &quot;10&quot;
        ///    , &quot;Sedna&quot;
        ///    , &quot;12&quot;
        ///    , &quot;13&quot;
        ///    , &quot;14&quot;
        ///    , &quot;Phobos&quot;
        ///    , &quot;16&quot;
        ///  ]
        ///}
        ///.
        /// </summary>
        public static string persistentEnemyData {
            get {
                return ResourceManager.GetString("persistentEnemyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;SolNode0&quot;: {
        ///    &quot;value&quot;: &quot;SolNode0&quot;,
        ///    &quot;enemy&quot;: &quot;Sentient&quot;,
        ///    &quot;type&quot; : &quot;Ancient Retribution&quot;
        ///  }
        ///  , &quot;SolNode1&quot;: {
        ///    &quot;value&quot;: &quot;Galatea (Neptune)&quot;,
        ///    &quot;enemy&quot;: &quot;Corpus&quot;,
        ///    &quot;type&quot; : &quot;Capture&quot;
        ///  }
        ///  , &quot;SolNode2&quot;: {
        ///    &quot;value&quot;: &quot;Aphrodite (Venus)&quot;,
        ///    &quot;enemy&quot;: &quot;Corpus&quot;,
        ///    &quot;type&quot; : &quot;Mobile Defense&quot;
        ///  }
        ///  , &quot;SolNode3&quot;: {
        ///    &quot;value&quot;: &quot;Cordelia (Uranus)&quot;,
        ///    &quot;enemy&quot;: &quot;Sentient&quot;,
        ///    &quot;type&quot; : &quot;Ancient Retribution&quot;
        ///  }
        ///  , &quot;SolNode4&quot;: {
        ///    &quot;value&quot;: &quot;Acheron (Pluto)&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string solNodes {
            get {
                return ResourceManager.GetString("solNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;modifierTypes&quot;: {
        ///    &quot;SORTIE_MODIFIER_LOW_ENERGY&quot;:&quot;Energy Reduction&quot;,
        ///    &quot;SORTIE_MODIFIER_IMPACT&quot;: &quot;Enemy Physical Enhancement: Impact&quot;,
        ///    &quot;SORTIE_MODIFIER_SLASH&quot;: &quot;Enemy Physical Enhancement: Slash&quot;,
        ///    &quot;SORTIE_MODIFIER_PUNCTURE&quot;: &quot;Enemy Physical Enhancement: Puncture&quot;,
        ///    &quot;SORTIE_MODIFIER_EXIMUS&quot;: &quot;Eximus Stronghold&quot;,
        ///    &quot;SORTIE_MODIFIER_MAGNETIC&quot;: &quot;Enemy Elemental Enhancement: Magnetic&quot;,
        ///    &quot;SORTIE_MODIFIER_CORROSIVE&quot;: &quot;Enemy Elemental Enhancement: Corrosive&quot;,
        ///    &quot;SORTIE_MODIFIER_V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sortieData {
            get {
                return ResourceManager.GetString("sortieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ArbitersSyndicate&quot;: {
        ///    &quot;name&quot;: &quot;Arbiters of Hexis&quot;
        ///  },
        ///  &quot;CephalonSudaSyndicate&quot;: {
        ///    &quot;name&quot;: &quot;Cephalon Suda&quot;
        ///  },
        ///  &quot;NewLokaSyndicate&quot;: {
        ///    &quot;name&quot;: &quot;New Loka&quot;
        ///  },
        ///  &quot;PerrinSyndicate&quot;: {
        ///    &quot;name&quot;: &quot;Perrin Sequence&quot;
        ///  },
        ///  &quot;SteelMeridianSyndicate&quot;: {
        ///    &quot;name&quot;: &quot;Steel Meridian&quot;
        ///  },
        ///  &quot;RedVeilSyndicate&quot;: {
        ///    &quot;name&quot;: &quot;Red Veil&quot;
        ///  }
        ///}.
        /// </summary>
        public static string syndicatesData {
            get {
                return ResourceManager.GetString("syndicatesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;GAMEPLAY_KILL_XP_AMOUNT&quot; : {
        ///    &quot;value&quot; : &quot;Mission Kill XP&quot;
        ///  },
        ///  &quot;GAMEPLAY_PICKUP_AMOUNT&quot; : {
        ///    &quot;value&quot; : &quot;Resource Drop Amount&quot;
        ///  },
        ///  &quot;GAMEPLAY_MONEY_REWARD_AMOUNT&quot; : {
        ///    &quot;value&quot; : &quot;Credit Drop chance&quot;
        ///  },
        ///  &quot;GAMEPLAY_MONEY_PICKUP_AMOUNT&quot; : {
        ///    &quot;value&quot; : &quot;Credit Drop amount&quot;
        ///  }
        ///}.
        /// </summary>
        public static string upgradeTypes {
            get {
                return ResourceManager.GetString("upgradeTypes", resourceCulture);
            }
        }
    }
}
